<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Arben Hajrizaj</title>
  </head>
  <body>
<?php

  $voornaam = "Arben";
  $achternaam = "Hajrizaj";
  $adres = "p.lastmanstraat";
  $huisnummer = "39";
  $plaats = "Enschede";
  $leeftijd = "18";

echo "
<img src='img\ava.png' width='100' height='100'></img>
<h1>voornaam: $voornaam</h1>
    <h1>achternaam: $achternaam</h1>
    <h2>adres: $adres</h2>
    <h2>huisnummer: $huisnummer</h2>
    <h2>plaats: $plaats</h2>
    <h3>leeftijd: $leeftijd</h3>"
?>
</body>
</html>
