<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>7t8df7</title>
  </head>
  <body>
    <?php

      $voornaam = "Damian";
      $achternaam = "Trojak";
      $adres = "Zunabrink";
      $huisnummer = "145";
      $plaats = "Enschede";
      $leeftijd = "16";

    echo "
        <h1>Naam: $voornaam $achternaam</h1>
        <h2>adres: $adres $huisnummer $plaats</h2>
        <h3>leeftijd: $leeftijd</h3>"
    ?>efsfes-0y9fuchvvoipycgh jbk
  </body>das
</html>
