<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
  </head>
  <body>
<?php
  $voornaam = "Peter";
  $achternaam = "Kuipers";
  $adres = "Billitonstraat";
  $huisnummer = "10A";
  $plaats = "Enschede";
  $leeftijd = "20";
echo "
    <img src='img\ava.png' width='100' height='100'></img>
    <h1>Naam: $voornaam $achternaam</h1>
    <h2>adres: $adres $huisnummer $plaats</h2>
    <h3>leeftijd: $leeftijd</h3>"
?>
</body>
</html>
